FROM bleshik/scala:2.11.5
ADD . /tmp
ENV SBT_OPTS="-Dsbt.override.build.repos=true -Dsbt.repository.config=repositories"
ENTRYPOINT echo $SBT_OPTS && export PATH=$JAVA_HOME/bin:$PATH && cd /tmp/backend/extractor && (echo "accessKey = $AWS_ACCESS_KEY_ID" ; echo "secretKey = $AWS_SECRET_ACCESS_KEY") >> ./src/main/resources/AwsCredentials.properties && sbt test && (sbt updateLambda || sbt createLambda)
