package wh.extractor.utkonos

import org.scalatest.{FlatSpec, Matchers}
import wh.extractor.{Category, ExtractedEntry}

class UtkonosExtractorSpec extends FlatSpec with Matchers {
  val rootCategory = Category("Продукты питания",null)
  val firstCategory = Category("Молочные продукты, мороженое", rootCategory)
  val secondCategory = Category("Молоко, сливки, молочные коктейли", firstCategory)
  "Utkonos extractor" should "return right list of entries" in {
    val extractor = new UtkonosExtractor(downloadImages = false)
    extractor.extract(getClass.getClassLoader.getResource("utkonos/1.html")).toList should be (
      List(
        ExtractedEntry("Utkonos", "Йогурт Valio питьевой Черешня 0,4%, 0,33мл", 5250, rootCategory),
        ExtractedEntry("Utkonos", "Вода СЕРЯБЬ Селивановская минеральная питьевая столовая газированная 0,33л пэт", 4700, rootCategory),
        ExtractedEntry("Utkonos", "Вода СЕРЯБЬ Селивановская минеральная питьевая столовая газированная 0,5л пэт", 5260, rootCategory),
        ExtractedEntry("Utkonos", "Вода СЕРЯБЬ Селивановская минеральная питьевая столовая негазированная 0,33л стекло", 7080, rootCategory),
        ExtractedEntry("Utkonos", "Вода СЕРЯБЬ Селивановская минеральная питьевая столовая негазированная 0,5л пэт спорт", 5670, rootCategory),
        ExtractedEntry("Utkonos", "Вода СЕРЯБЬ Селивановская минеральная питьевая столовая негазированная 0,75л пэт спорт", 6050, rootCategory),
        ExtractedEntry("Utkonos", "Мука Molini Pizzuti пшеничная \"Per Dolci\" для кондитерских изделий, 1кг", 13700, rootCategory),
        ExtractedEntry("Utkonos", "Мука Molini Pizzuti пшеничная \"Per Pasne\" для хлеба, 1кг", 13700, rootCategory),
        ExtractedEntry("Utkonos", "Мука Molini Pizzuti пшеничная \"Per Pasta\", 1кг", 15500, rootCategory),
        ExtractedEntry("Utkonos", "Напиток KОХХ Закат Европы тонизирующий безалкогольный газированный, 250мл", 8500, rootCategory),
        ExtractedEntry("Utkonos", "Напиток KОХХ Северная аврора тонизирующий безалкогольный газированный, 250мл", 8500, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ochakovo Джин & Тоник слабоалкогольный газированный 9%, 0,5л ж/б", 8480, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ochakovo Джин-Грейпфрут слабоалкогольный газированный 9%, 0,5л ж/б", 8480, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ochakovo Мохито Клубничный слабоалкогольный газированный 7,2%, 0,5л", 7830, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ochakovo Сидор слабоалкогольный газированный 9%, 1л", 15000, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ярис Ярый тонизирующий безалкогольный негазированный с натуральным соком растительными экстрактами 200мл стекл", 5410, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ярис Ярый тонизирующий безалкогольный негазированный с натуральным соком растительными экстрактами 250мл ПЭТ", 5410, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ярис Ясный тонизирующий безалкогольный негазированный с натуральным соком растительными экстрактами 200мл стек", 5410, rootCategory),
        ExtractedEntry("Utkonos", "Напиток Ярис Ясный тонизирующий безалкогольный негазированный с натуральным соком растительными экстрактами 250мл ПЭТ", 5410, rootCategory),
        ExtractedEntry("Utkonos", "Рис Campanini Nero Venere среднего размера черный, 1кг", 50100, rootCategory),
        ExtractedEntry("Utkonos", "Шоколад Kinder молочный Макси, 4*21г", 5890, rootCategory),
        ExtractedEntry("Utkonos", "Молоко Агуша стерилизованное с витаминами А и С 3,2%, 0,5л", 2720, firstCategory),
        ExtractedEntry("Utkonos", "Десерт творожный Чудо творожок воздушный Вишня-Черешня 4%,100г", 1690, firstCategory),
        ExtractedEntry("Utkonos", "Десерт творожный Чудо творожок воздушный Клубника-Земляника 4%,115г", 1690, firstCategory),
        ExtractedEntry("Utkonos", "Сливки Чистый Край 10%, 0,5л", 17400, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Чистый Край отборное пастеризованное 3,4-4,2%, 1л", 10100, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Караваево Деревенское пастеризованное 1,5%, 930г", 8450, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Караваево Отборное пастеризованное 3,4-6%, 750г", 7260, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Караваево топленое деревенское 3,2%, 450г", 4690, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Молочная культура пастеризованное 3,5-4,5%, 500г", 7680, secondCategory),
        ExtractedEntry("Utkonos", "Коктейль Новая деревня молочный шоколадный 2,5%, 1л", 9020, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Parmalat ультрапастеризованное 3,5%, 12*1л", 80300, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Рузское пастеризованное 1,5%, 1000г", 11100, secondCategory),
        ExtractedEntry("Utkonos", "Напиток Актуаль Грейпфрут сыворотка с соком, 930г", 7280, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 3,2%, 950г", 6700, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Ясный луг ультрапастеризованное 3,2%, 1л", 4880, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино отборное пастеризованное 3,4-4,5%, 0,93л", 5560, secondCategory),
        ExtractedEntry("Utkonos", "Молоко М Лианозовское ультрапастеризованное 3,2%, 950г", 5180, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Домик в деревне 10% стерилизованные, 480г", 7470, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне 1,5%, 950г", 6100, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Утренней дойки отборное пастеризованное 3,4-6%, 1л", 8320, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Нашей дойки пастеризованное 3,4-6%, 1л", 6480, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино ультрапастеризованное 2,5%, 0,95л", 5900, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Агуша стерилизованное с витаминами А и С 3,2%, 0,5л", 2720, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино ультрапастеризованное 3,2%, 0,95л", 6800, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Parmalat ультрапастеризованное 3,5%, 1л", 7260, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 0,5%, 950г", 5900, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Агуша с витаминами \"А\" и \"С\" с 8 месяцев 2,5%, 0,2л", 2210, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Домик в деревне питьевые стерилизованные 10%, 200г", 4300, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино пастеризованное 2,5%, 0,93л", 5980, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Рузское пастеризованное 3,2%-4,0%, 1000г", 10900, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Parmalat ультрапастеризованное 0,5%, 1л", 5920, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Parmalat ультрапастеризованное 1,8%, 1л", 6530, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Тёма питьевое ультрапастеризованное с кальцием 3,2%, 0,5л", 4060, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Домик в деревне 20%, 200г", 7180, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Останкинское пастеризованное 36 копеек 3,2%, 900г", 5340, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 2,5%, 950г", 6860, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 3,2%, 500г", 4330, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Новая деревня отборное пастеризованное 3,5%, 1л", 8540, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Агуша стерилизованное детское с пребиотиком для детей с 12 месяцев 2,5%, 0,2л", 2790, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Домик в деревне стерилизованные 20%, 480г", 14100, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне топленое ультрапастеризованное 3,2%, 950г", 7910, secondCategory),
        ExtractedEntry("Utkonos", "Коктейль молочный Смешарики Ванильное мороженое 2,5%, 210г", 2660, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 6%, 950г", 9280, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино ультрапастеризованное 1,5%, 0,95л", 6650, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Из Вологды ультрапастеризованное 3,2%, 0,2л", 2150, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Домик в деревне 10%, 750г", 10900, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Белый город питьевые ультрапастеризованные 10%, 200г", 3450, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Простоквашино 10%, 350г", 6190, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Петмол ультрапастеризованные 11%, 500г", 8970, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Агуша Я сам Иммунити стерилизованное с витаминами и минералами 2,5%, 0,5л", 5240, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Простоквашино топленое 4%, 0,93л", 6630, secondCategory),
        ExtractedEntry("Utkonos", "Сливки Петмол для взбивания ультрапастеризованные 33%, 0,5л", 16100, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Домик в деревне ультрапастеризованное 2,5%, 1450г", 9840, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Брест-Литовск ультрапастеризованное 2,8%, 1л", 6020, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Parmalat ультрапастеризованное Диеталат 0,5%, 1л", 6530, secondCategory),
        ExtractedEntry("Utkonos", "Коктейль молочный Смешарики Карамельная ириска 2,5%, 210г", 2660, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Белый город ультрапастеризованное 2,5%, 1л", 5760, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Тема питьевое ультрапастеризованное для детей с 8 месяцев 3,2%, 200г", 2160, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Брест-Литовск питьевое ультрапастеризованное 3,6%, 1л", 6570, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Ясный луг ультрапастеризованное 1,5%, 1л", 5720, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Белый город ультрапастеризованное 3,2%, 1л", 6210, secondCategory),
        ExtractedEntry("Utkonos", "Молоко Новая деревня пастеризованное 2,5%, 1л", 8090, secondCategory),
        ExtractedEntry("Utkonos", "Коктейль молочный Смешарики Клубника 2,5%, 210г", 2660, secondCategory)
      )
    )
  }
}
